### ISSUE TITLE
Failure to create an AEM Asset

### ISSUE THREAD

**Issue by schaefa** [wcm-io/io.wcm.testing.aem-mock#27]
After upgrading from 4.1.0 to 4.1.2 I am running into an issue when I want to create an asset with the ContentBuilder.asset() - here with no image data just height, width and mime-type:

I see this exceptions:

java.lang.IllegalStateException: Unable to enable secure processing.
	at org.apache.sling.contentparser.xml.jcr.internal.JCRXMLContentParser.<init>(JCRXMLContentParser.java:61)
	at org.apache.sling.testing.mock.sling.loader.ContentLoader.<init>(ContentLoader.java:149)
	at org.apache.sling.testing.mock.sling.loader.ContentLoader.<init>(ContentLoader.java:122)
	at io.wcm.testing.mock.aem.dam.MockAssetManager.<init>(MockAssetManager.java:79)
	at io.wcm.testing.mock.aem.dam.MockAemDamAdapterFactory.getAdapter(MockAemDamAdapterFactory.java:88)
	at io.wcm.testing.mock.aem.dam.MockAemDamAdapterFactory.getAdapter(MockAemDamAdapterFactory.java:69)
	at org.apache.sling.testing.mock.sling.MockAdapterManagerImpl.getAdapter(MockAdapterManagerImpl.java:149)
	at org.apache.sling.testing.mock.sling.ThreadsafeMockAdapterManagerWrapper.getAdapter(ThreadsafeMockAdapterManagerWrapper.java:48)
	at org.apache.sling.api.adapter.SlingAdaptable.adaptTo(SlingAdaptable.java:104)
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.adaptTo(ResourceResolverImpl.java:818)
	at io.wcm.testing.mock.aem.builder.ContentBuilder.asset(ContentBuilder.java:349)
	at io.wcm.testing.mock.aem.builder.ContentBuilder.asset(ContentBuilder.java:309)
...
Caused by: org.xml.sax.SAXNotRecognizedException: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
	at org.apache.xerces.parsers.AbstractSAXParser.setFeature(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.setFeatures(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParserImpl(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.setFeature(Unknown Source)
	at org.apache.sling.contentparser.xml.jcr.internal.JCRXMLContentParser.<init>(JCRXMLContentParser.java:57)

I am using the latest AEM SDK API and Java 11.

**Comment by stefanseifert** [comment]
difficult to tell without more context - version 4.1.2 was released two years ago and is used in lots of projects since then without any complaint - so there has to be some issue in your actual setup (classpath or JDK). also, probably try to use the latest version (also the issue sounds as that will not fix the problem).
probably a different or outdated XML parser/xerces version is used here, or sneaked in as transitive dependency in the classpath.
